// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ8Tw6H4S0V9cRAX6xY7YbVCw6nB3YteU',
    appId: '1:297048515484:web:fb6a990e09d8565e275e59',
    messagingSenderId: '297048515484',
    projectId: 'chat-bridge-f9a1a',
    authDomain: 'chat-bridge-f9a1a.firebaseapp.com',
    storageBucket: 'chat-bridge-f9a1a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArcEhxTmvbsYc6AfmXWcwzkUrwaDAagB8',
    appId: '1:297048515484:android:18415ce43c5682df275e59',
    messagingSenderId: '297048515484',
    projectId: 'chat-bridge-f9a1a',
    storageBucket: 'chat-bridge-f9a1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVL3E8GggP7X_DMUFZHvR1XSxsV62Ocq8',
    appId: '1:297048515484:ios:87ec86cf134a6086275e59',
    messagingSenderId: '297048515484',
    projectId: 'chat-bridge-f9a1a',
    storageBucket: 'chat-bridge-f9a1a.appspot.com',
    iosClientId: '297048515484-j6hqtelct1ueqjeedtqr70o2b9li87cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatBridge',
  );
}
